language: node_js
node_js:
  - "20" # Specify the Node.js version or use latest version if you want

# Install dependencies
install:
  - npm install

# Run the build step if needed
script:
  - npm run format # Format code
  - npm run test # Run dist
  - npm run test-integration # Run dist with NYC covergae
